version: "2"

services:
    server:
      image: prefecthq/prefect:2.14.17-python3.11
      restart: always
      volumes:
        - ./data:/root/.prefect
      entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
      environment:
        - PREFECT_UI_URL=http://127.0.0.1:4200/api
        - PREFECT_API_URL=http://127.0.0.1:4200/api
        - PREFECT_SERVER_API_HOST=0.0.0.0
      ports:
        - 4200:4200
    
    agent:
      build: .
      environment:
        - PREFECT_UI_URL=http://mlops-server.docker.local:4200/api
        - PREFECT_API_URL=http://mlops-server.docker.local:4200/api
        - PREFECT_SERVER_API_HOST=mlops-server.docker.local