version: '2'

services:
  webserver:
    image: apache/airflow:2.2.3
    command: webserver
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
  scheduler:
    image: apache/airflow:2.2.3
    command: scheduler
  worker:
    image: apache/airflow:2.2.3
    command: worker