version: '2'

services:
    jupyter:
      image: jupyter/base-notebook
      ports:
        - "8888:8888"
      volumes:
        - .:/home/jovyan/work
      environment:
        - JUPYTER_ENABLE_LAB=yes
      command: start-notebook.sh --NotebookApp.token=''
        